services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=toor
      - POSTGRES_DB=bank
    restart:
      always

  account-service:
    container_name: account-service
    image: account-service
    build: ./account-service
    ports:
      - 2525:20025
    depends_on:
      - postgres
    restart:
      always
    env_file:
      - ./account-service/config.env

  postgres-journal:
    container_name: postgres-journal
    image: postgres
    ports:
      - 5434:5432
    volumes:
      - ~/data/postgres-journal:/var/lib/postgresql/data
    env_file:
      - ./journal-service/pg-docker.env
    restart:
      always

  journal-service:
    container_name: journal-service
    image: journal-service
    build: ./journal-service
    ports:
      - 20026:20026
    depends_on:
      - postgres-journal
    restart:
      always
    env_file:
      - ./journal-service/config.env